### ISSUE TITLE
Issue with game: S. Carolina State @ Bryant

### ISSUE THREAD

**Issue by USSAnon** [Watchful1/CFBRef#100]
Trying to understand the bot.  Twice we have had what I feel is an issue.  When inputting a number where the difference of the two choices from O and D are over 1000, the computer puts it in as just the 3 digit number.  Example below:
It's a run to the left for 3 yard(s)! First down South Carolina State!(!)

The play took 19 seconds, 3:40 left

It's 1st and 10 on the Bryant 36. 3:40 left in the 1st.

Offense: 413

Defense: 1476

Difference: 437

Is it supposed to be this way?  Thank you for your help.

**Comment by Watchful1** [comment]
That's correct. It wraps around the end. The biggest difference you can get is 750.

See the Play Mechanics section of the rulebook https://docs.google.com/document/d/1gHaVQqpOpcJGN0AkqABvvY3DiTbqEAgWIvQECgTeqNo/edit#heading=h.67vy3ej7nv0r
