### ISSUE TITLE
Compile stats

### ISSUE THREAD

**Issue by Watchful1** [Watchful1/CFBRef#50]

**Comment by ZenSunshine** [comment]
Average difference between chosen numbers for each team while on offense and defense.
Total yards, passing yards, rushing yards, turnovers, time of possession, average starting field position, field goal %, rushing yards per attempt, passing yards per attempt, yards per play, longest rushing play, longest passing play, points per play, points per drive, number of delay of game penalties, average punt length, red zone scoring %, 4th down conversion %, number of defensive touchdowns.

All these stats per game and cumulative for the season per team.

**Comment by Watchful1** [comment]
I'm going to take the approach of just posting a list of each play rather than compiling more stats. These will be posted in the postgame thread.
