### ISSUE TITLE
Need to fix message if user loses coin toss

### ISSUE THREAD

**Issue by zenverak** [Watchful1/CFBRef#51]
https://github.com/Watchful1/CFBRef/blob/9ce9895b6747f502632f7af22ef9110d919c184b/src/messages.py#L110

I believe this portion

`  game['away']['home']`

Should be `game['home']['name']`

**Comment by zenverak** [comment]
I believe this is correct. I tested it on version and it seems to work.

**Comment by Watchful1** [comment]
Fixed
