### ISSUE TITLE
In normal plays ( and others) timemessage will be None and you can't join string with none

### ISSUE THREAD

**Issue by zenverak** [Watchful1/CFBRef#52]
https://github.com/Watchful1/CFBRef/blob/9ce9895b6747f502632f7af22ef9110d919c184b/src/state.py#L671

I noticed that when I was testing this out that It kept erroring out on result of play. I then printed the messages at each stage since it stated that it couldn't join None. 

I realized the None portion game from  the above. 

I think the reason is because if you look a normal play, lets say  a run, it doesn't set any time messages. So when you get to this point, it states,   if timemessage not none, which it will always be none for those types of a plays. i think it needs to be   `if timeMessage is None`  . The reason being that I do believe that for the messages that don't have a defined timeMessage ( such as normal plays) you will want to get this message. However, you have the other messages, such as kneel that you set prior. In those cases timeMessage will already be set so you won't want to change the timeMessage there.

**Comment by Watchful1** [comment]
Fixed
