### ISSUE TITLE
Unable to send Kickoff Number

### ISSUE THREAD

**Issue by jonnyshaw10** [Watchful1/CFBRef#96]
In the Abilene Christian v Prairie View A&M game I received the message to send a number for the kickoff and when I send a number it replies back saying it’s not needing a kickoff number for our game so we are stuck right now

usernames for Reddit is u/jms14b

**Comment by jonnyshaw10** [comment]
Reddit username is u/jms14b

**Comment by Watchful1** [comment]
Errors should be reported on discord or reddit, this is for feature requests. I don't check it that often
